name: Documentation

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r docs/requirements.txt

      - name: Register Jupyter kernel
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Sphinx Build
        run: |
          cd docs
          make clean
          make html
          cd ../

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/build/html/

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: docs/build/html/

      - name: Deploy to stephenmwilkins.github.io/synthpop
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: stephenmwilkins/stephenmwilkins.github.io
          publish_dir: docs/build/html
          destination_dir: synthpop
          keep_files: false
